// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Postgres.Item.Recovery
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecoveryPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Datadog API key to use for monitoring the new database. Defaults to the API key of the original database. Use an empty string to prevent copying of the API key to the new database.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatadogApiKey { get; set; }
#nullable restore
#else
        public string DatadogApiKey { get; set; }
#endif
        /// <summary>Datadog region code to use for monitoring the new database. Defaults to the region code of the original database. Use an empty string to prevent copying of the region code to the new database.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatadogSite { get; set; }
#nullable restore
#else
        public string DatadogSite { get; set; }
#endif
        /// <summary>The environment to create the new database in. Defaults to the environment of the original database.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentId { get; set; }
#nullable restore
#else
        public string EnvironmentId { get; set; }
#endif
        /// <summary>The plan to use for the new database. Defaults to the same plan as the original database. Cannot be a lower tier plan than the original database.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Plan { get; set; }
#nullable restore
#else
        public string Plan { get; set; }
#endif
        /// <summary>Name of the new database.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RestoreName { get; set; }
#nullable restore
#else
        public string RestoreName { get; set; }
#endif
        /// <summary>The point in time to restore the database to. See `/recovery-info` for restore availability</summary>
        public DateTimeOffset? RestoreTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Postgres.Item.Recovery.RecoveryPostRequestBody"/> and sets the default values.
        /// </summary>
        public RecoveryPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Postgres.Item.Recovery.RecoveryPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Postgres.Item.Recovery.RecoveryPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Postgres.Item.Recovery.RecoveryPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "datadogApiKey", n => { DatadogApiKey = n.GetStringValue(); } },
                { "datadogSite", n => { DatadogSite = n.GetStringValue(); } },
                { "environmentId", n => { EnvironmentId = n.GetStringValue(); } },
                { "plan", n => { Plan = n.GetStringValue(); } },
                { "restoreName", n => { RestoreName = n.GetStringValue(); } },
                { "restoreTime", n => { RestoreTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("datadogApiKey", DatadogApiKey);
            writer.WriteStringValue("datadogSite", DatadogSite);
            writer.WriteStringValue("environmentId", EnvironmentId);
            writer.WriteStringValue("plan", Plan);
            writer.WriteStringValue("restoreName", RestoreName);
            writer.WriteDateTimeOffsetValue("restoreTime", RestoreTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
