// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.NotificationSettings.Owners.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithOwnerGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The emailEnabled property</summary>
        public bool? EmailEnabled { get; set; }
        /// <summary>The notificationsToSend property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? NotificationsToSend { get; set; }
#nullable restore
#else
        public UntypedNode NotificationsToSend { get; set; }
#endif
        /// <summary>The ownerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The previewNotificationsEnabled property</summary>
        public bool? PreviewNotificationsEnabled { get; set; }
        /// <summary>The slackEnabled property</summary>
        public bool? SlackEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.NotificationSettings.Owners.Item.WithOwnerGetResponse"/> and sets the default values.
        /// </summary>
        public WithOwnerGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.NotificationSettings.Owners.Item.WithOwnerGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.NotificationSettings.Owners.Item.WithOwnerGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.NotificationSettings.Owners.Item.WithOwnerGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "emailEnabled", n => { EmailEnabled = n.GetBoolValue(); } },
                { "notificationsToSend", n => { NotificationsToSend = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "previewNotificationsEnabled", n => { PreviewNotificationsEnabled = n.GetBoolValue(); } },
                { "slackEnabled", n => { SlackEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("emailEnabled", EmailEnabled);
            writer.WriteObjectValue<UntypedNode>("notificationsToSend", NotificationsToSend);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteBoolValue("previewNotificationsEnabled", PreviewNotificationsEnabled);
            writer.WriteBoolValue("slackEnabled", SlackEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
