// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Render.OpenApiClient.Metrics.ActiveConnections;
using Soenneker.Render.OpenApiClient.Metrics.Bandwidth;
using Soenneker.Render.OpenApiClient.Metrics.BandwidthSources;
using Soenneker.Render.OpenApiClient.Metrics.Cpu;
using Soenneker.Render.OpenApiClient.Metrics.CpuLimit;
using Soenneker.Render.OpenApiClient.Metrics.CpuTarget;
using Soenneker.Render.OpenApiClient.Metrics.DiskCapacity;
using Soenneker.Render.OpenApiClient.Metrics.DiskUsage;
using Soenneker.Render.OpenApiClient.Metrics.Filters;
using Soenneker.Render.OpenApiClient.Metrics.HttpLatency;
using Soenneker.Render.OpenApiClient.Metrics.HttpRequests;
using Soenneker.Render.OpenApiClient.Metrics.InstanceCount;
using Soenneker.Render.OpenApiClient.Metrics.Memory;
using Soenneker.Render.OpenApiClient.Metrics.MemoryLimit;
using Soenneker.Render.OpenApiClient.Metrics.MemoryTarget;
using Soenneker.Render.OpenApiClient.Metrics.ReplicationLag;
using Soenneker.Render.OpenApiClient.Metrics.TaskRunsCompleted;
using Soenneker.Render.OpenApiClient.Metrics.TaskRunsQueued;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Render.OpenApiClient.Metrics
{
    /// <summary>
    /// Builds and executes requests for operations under \metrics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetricsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activeConnections property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.ActiveConnections.ActiveConnectionsRequestBuilder ActiveConnections
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.ActiveConnections.ActiveConnectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bandwidth property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.Bandwidth.BandwidthRequestBuilder Bandwidth
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.Bandwidth.BandwidthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bandwidthSources property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.BandwidthSources.BandwidthSourcesRequestBuilder BandwidthSources
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.BandwidthSources.BandwidthSourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cpu property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.Cpu.CpuRequestBuilder Cpu
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.Cpu.CpuRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cpuLimit property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.CpuLimit.CpuLimitRequestBuilder CpuLimit
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.CpuLimit.CpuLimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cpuTarget property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.CpuTarget.CpuTargetRequestBuilder CpuTarget
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.CpuTarget.CpuTargetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The diskCapacity property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.DiskCapacity.DiskCapacityRequestBuilder DiskCapacity
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.DiskCapacity.DiskCapacityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The diskUsage property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.DiskUsage.DiskUsageRequestBuilder DiskUsage
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.DiskUsage.DiskUsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filters property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.Filters.FiltersRequestBuilder Filters
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.Filters.FiltersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The httpLatency property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.HttpLatency.HttpLatencyRequestBuilder HttpLatency
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.HttpLatency.HttpLatencyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The httpRequests property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.HttpRequests.HttpRequestsRequestBuilder HttpRequests
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.HttpRequests.HttpRequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The instanceCount property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.InstanceCount.InstanceCountRequestBuilder InstanceCount
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.InstanceCount.InstanceCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memory property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.Memory.MemoryRequestBuilder Memory
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.Memory.MemoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memoryLimit property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.MemoryLimit.MemoryLimitRequestBuilder MemoryLimit
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.MemoryLimit.MemoryLimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memoryTarget property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.MemoryTarget.MemoryTargetRequestBuilder MemoryTarget
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.MemoryTarget.MemoryTargetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The replicationLag property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.ReplicationLag.ReplicationLagRequestBuilder ReplicationLag
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.ReplicationLag.ReplicationLagRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The taskRunsCompleted property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.TaskRunsCompleted.TaskRunsCompletedRequestBuilder TaskRunsCompleted
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.TaskRunsCompleted.TaskRunsCompletedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The taskRunsQueued property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.TaskRunsQueued.TaskRunsQueuedRequestBuilder TaskRunsQueued
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.TaskRunsQueued.TaskRunsQueuedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Metrics.MetricsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetricsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Metrics.MetricsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetricsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
