// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Render.OpenApiClient.Sandboxes.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Render.OpenApiClient.Sandboxes
{
    /// <summary>
    /// Builds and executes requests for operations under \sandboxes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SandboxesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Render.OpenApiClient.sandboxes.item collection</summary>
        /// <param name="position">The ID of the sandbox</param>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Sandboxes.Item.WithSandboxItemRequestBuilder"/></returns>
        public global::Soenneker.Render.OpenApiClient.Sandboxes.Item.WithSandboxItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sandboxId", position);
                return new global::Soenneker.Render.OpenApiClient.Sandboxes.Item.WithSandboxItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Sandboxes.SandboxesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SandboxesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sandboxes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Sandboxes.SandboxesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SandboxesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sandboxes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
