// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Render.OpenApiClient.Models;
using Soenneker.Render.OpenApiClient.Registrycredentials.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Render.OpenApiClient.Registrycredentials
{
    /// <summary>
    /// Builds and executes requests for operations under \registrycredentials
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RegistrycredentialsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Render.OpenApiClient.registrycredentials.item collection</summary>
        /// <param name="position">The ID of the registry credential</param>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Registrycredentials.Item.WithRegistryCredentialItemRequestBuilder"/></returns>
        public global::Soenneker.Render.OpenApiClient.Registrycredentials.Item.WithRegistryCredentialItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("registryCredentialId", position);
                return new global::Soenneker.Render.OpenApiClient.Registrycredentials.Item.WithRegistryCredentialItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrycredentialsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registrycredentials{?createdAfter*,createdBefore*,cursor*,limit*,name,ownerId,type,updatedAfter*,updatedBefore*,username}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrycredentialsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registrycredentials{?createdAfter*,createdBefore*,cursor*,limit*,name,ownerId,type,updatedAfter*,updatedBefore*,username}", rawUrl)
        {
        }
        /// <summary>
        /// List registry credentials matching the provided filters. If no filters are provided, returns all registry credentials you have permissions to view.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Render.OpenApiClient.Models.RegistryCredential&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Render.OpenApiClient.Models.RegistryCredential>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder.RegistrycredentialsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Render.OpenApiClient.Models.RegistryCredential>> GetAsync(Action<RequestConfiguration<global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder.RegistrycredentialsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Render.OpenApiClient.Models.RegistryCredential>(requestInfo, global::Soenneker.Render.OpenApiClient.Models.RegistryCredential.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create a new registry credential.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.RegistryCredential"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Render.OpenApiClient.Models.RegistryCredential?> PostAsync(global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Render.OpenApiClient.Models.RegistryCredential> PostAsync(global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Render.OpenApiClient.Models.RegistryCredential>(requestInfo, global::Soenneker.Render.OpenApiClient.Models.RegistryCredential.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List registry credentials matching the provided filters. If no filters are provided, returns all registry credentials you have permissions to view.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder.RegistrycredentialsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder.RegistrycredentialsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new registry credential.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List registry credentials matching the provided filters. If no filters are provided, returns all registry credentials you have permissions to view.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RegistrycredentialsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter for services created after a certain time (specified as an ISO 8601 timestamp)</summary>
            [QueryParameter("createdAfter")]
            public DateTimeOffset? CreatedAfter { get; set; }
            /// <summary>Filter for services created before a certain time (specified as an ISO 8601 timestamp)</summary>
            [QueryParameter("createdBefore")]
            public DateTimeOffset? CreatedBefore { get; set; }
            /// <summary>The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Filter for the name of a credential</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string[]? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string[] Name { get; set; }
#endif
            /// <summary>The ID of the workspaces to return resources for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ownerId")]
            public string[]? OwnerId { get; set; }
#nullable restore
#else
            [QueryParameter("ownerId")]
            public string[] OwnerId { get; set; }
#endif
            /// <summary>Filter for the registry type for the credential</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public global::Soenneker.Render.OpenApiClient.Models.RegistryCredentialRegistry[]? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public global::Soenneker.Render.OpenApiClient.Models.RegistryCredentialRegistry[] Type { get; set; }
#endif
            /// <summary>Filter for services updated after a certain time (specified as an ISO 8601 timestamp)</summary>
            [QueryParameter("updatedAfter")]
            public DateTimeOffset? UpdatedAfter { get; set; }
            /// <summary>Filter for services updated before a certain time (specified as an ISO 8601 timestamp)</summary>
            [QueryParameter("updatedBefore")]
            public DateTimeOffset? UpdatedBefore { get; set; }
            /// <summary>Filter for the username of a credential</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("username")]
            public string[]? Username { get; set; }
#nullable restore
#else
            [QueryParameter("username")]
            public string[] Username { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
