// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Render.OpenApiClient.Models;
using Soenneker.Render.OpenApiClient.Services.Item.Autoscaling;
using Soenneker.Render.OpenApiClient.Services.Item.Cache;
using Soenneker.Render.OpenApiClient.Services.Item.CustomDomains;
using Soenneker.Render.OpenApiClient.Services.Item.Deploys;
using Soenneker.Render.OpenApiClient.Services.Item.EnvVars;
using Soenneker.Render.OpenApiClient.Services.Item.Events;
using Soenneker.Render.OpenApiClient.Services.Item.Headers;
using Soenneker.Render.OpenApiClient.Services.Item.Instances;
using Soenneker.Render.OpenApiClient.Services.Item.Jobs;
using Soenneker.Render.OpenApiClient.Services.Item.Preview;
using Soenneker.Render.OpenApiClient.Services.Item.Restart;
using Soenneker.Render.OpenApiClient.Services.Item.Resume;
using Soenneker.Render.OpenApiClient.Services.Item.Rollback;
using Soenneker.Render.OpenApiClient.Services.Item.Routes;
using Soenneker.Render.OpenApiClient.Services.Item.Scale;
using Soenneker.Render.OpenApiClient.Services.Item.SecretFiles;
using Soenneker.Render.OpenApiClient.Services.Item.Suspend;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Render.OpenApiClient.Services.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \services\{serviceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithServiceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The autoscaling property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Autoscaling.AutoscalingRequestBuilder Autoscaling
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Autoscaling.AutoscalingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cache property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Cache.CacheRequestBuilder Cache
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Cache.CacheRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customDomains property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.CustomDomains.CustomDomainsRequestBuilder CustomDomains
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.CustomDomains.CustomDomainsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deploys property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysRequestBuilder Deploys
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The envVars property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.EnvVars.EnvVarsRequestBuilder EnvVars
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.EnvVars.EnvVarsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The headers property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Headers.HeadersRequestBuilder Headers
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Headers.HeadersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The instances property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Instances.InstancesRequestBuilder Instances
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Instances.InstancesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The preview property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Preview.PreviewRequestBuilder Preview
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Preview.PreviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restart property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Restart.RestartRequestBuilder Restart
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Restart.RestartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resume property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Resume.ResumeRequestBuilder Resume
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Resume.ResumeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rollback property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Rollback.RollbackRequestBuilder Rollback
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Rollback.RollbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The routes property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Routes.RoutesRequestBuilder Routes
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Routes.RoutesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scale property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Scale.ScaleRequestBuilder Scale
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Scale.ScaleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secretFiles property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.SecretFiles.SecretFilesRequestBuilder SecretFiles
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.SecretFiles.SecretFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The suspend property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Suspend.SuspendRequestBuilder Suspend
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.Item.Suspend.SuspendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Services.Item.WithServiceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithServiceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/services/{serviceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Services.Item.WithServiceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithServiceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/services/{serviceId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete the service with the provided ID.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 410 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "410", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve the service with the provided ID.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.Service"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 410 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Render.OpenApiClient.Models.Service?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Render.OpenApiClient.Models.Service> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "410", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Render.OpenApiClient.Models.Service>(requestInfo, global::Soenneker.Render.OpenApiClient.Models.Service.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update the service with the provided ID.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.Service"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 410 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Render.OpenApiClient.Models.Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Render.OpenApiClient.Models.Service?> PatchAsync(global::Soenneker.Render.OpenApiClient.Models.ServicePATCH body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Render.OpenApiClient.Models.Service> PatchAsync(global::Soenneker.Render.OpenApiClient.Models.ServicePATCH body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "410", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Render.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Render.OpenApiClient.Models.Service>(requestInfo, global::Soenneker.Render.OpenApiClient.Models.Service.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete the service with the provided ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieve the service with the provided ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update the service with the provided ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Render.OpenApiClient.Models.ServicePATCH body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Render.OpenApiClient.Models.ServicePATCH body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Services.Item.WithServiceItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Render.OpenApiClient.Services.Item.WithServiceItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Render.OpenApiClient.Services.Item.WithServiceItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
