// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>The status of the event</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuditLog_status
    {
        [EnumMember(Value = "success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
