// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>Deprecated: use `autoDeployTrigger` instead. You can&apos;t set both `autoDeploy` and `autoDeployTrigger` in the same request.- `yes` is equivalent to `autoDeployTrigger: commit`.- `no` is equivalent to `autoDeployTrigger: off`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Obsolete("")]
    public enum AutoDeploy
    {
        [EnumMember(Value = "yes")]
        #pragma warning disable CS1591
        Yes,
        #pragma warning restore CS1591
        [EnumMember(Value = "no")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
    }
}
