// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BuildPlan
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "starter")]
        #pragma warning disable CS1591
        Starter,
        #pragma warning restore CS1591
        [EnumMember(Value = "performance")]
        #pragma warning disable CS1591
        Performance,
        #pragma warning restore CS1591
    }
}
