// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Cache_profile
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "no-cache")]
        #pragma warning disable CS1591
        NoCache,
        #pragma warning restore CS1591
        [EnumMember(Value = "origin-controlled")]
        #pragma warning disable CS1591
        OriginControlled,
        #pragma warning restore CS1591
        [EnumMember(Value = "origin-controlled-all")]
        #pragma warning disable CS1591
        OriginControlledAll,
        #pragma warning restore CS1591
    }
}
