// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateWorkflowRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Controls autodeploy behavior. &quot;commit&quot; deploys when a commit is pushed to the branch. &quot;checksPass&quot; waits for CI checks to pass before deploying. &quot;off&quot; disables autodeploy.</summary>
        public global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestAutoDeployTrigger? AutoDeployTrigger { get; set; }
        /// <summary>The buildConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestBuildConfig? BuildConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestBuildConfig BuildConfig { get; set; }
#endif
        /// <summary>The envVars property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvVars { get; set; }
#nullable restore
#else
        public string EnvVars { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ownerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>Defaults to &quot;oregon&quot;</summary>
        public global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestRegion? Region { get; set; }
        /// <summary>The command to run the workflow. Cannot be blank.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunCommand { get; set; }
#nullable restore
#else
        public string RunCommand { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequest"/> and sets the default values.
        /// </summary>
        public CreateWorkflowRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoDeployTrigger", n => { AutoDeployTrigger = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestAutoDeployTrigger>(); } },
                { "buildConfig", n => { BuildConfig = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestBuildConfig>(global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestBuildConfig.CreateFromDiscriminatorValue); } },
                { "envVars", n => { EnvVars = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestRegion>(); } },
                { "runCommand", n => { RunCommand = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestAutoDeployTrigger>("autoDeployTrigger", AutoDeployTrigger);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestBuildConfig>("buildConfig", BuildConfig);
            writer.WriteStringValue("envVars", EnvVars);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.CreateWorkflowRequestRegion>("region", Region);
            writer.WriteStringValue("runCommand", RunCommand);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
