// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DatabaseRole
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "primary")]
        #pragma warning disable CS1591
        Primary,
        #pragma warning restore CS1591
        [EnumMember(Value = "replica")]
        #pragma warning disable CS1591
        Replica,
        #pragma warning restore CS1591
    }
}
