// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>Current status of a dedicated IP set.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DedicatedIpStatus
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREATING")]
        #pragma warning disable CS1591
        Creating,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUNNING")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETING")]
        #pragma warning disable CS1591
        Deleting,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETED")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
