// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Deploy : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The commit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Deploy_commit? Commit { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Deploy_commit Commit { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The finishedAt property</summary>
        public DateTimeOffset? FinishedAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Image information used when creating the deploy. Not present for Git-backed deploys</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Deploy_image? Image { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Deploy_image Image { get; set; }
#endif
        /// <summary>The startedAt property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.DeployStatus? Status { get; set; }
        /// <summary>The trigger property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.Deploy_trigger? Trigger { get; set; }
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.Deploy"/> and sets the default values.
        /// </summary>
        public Deploy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.Deploy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.Deploy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.Deploy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commit", n => { Commit = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Deploy_commit>(global::Soenneker.Render.OpenApiClient.Models.Deploy_commit.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "finishedAt", n => { FinishedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image", n => { Image = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Deploy_image>(global::Soenneker.Render.OpenApiClient.Models.Deploy_image.CreateFromDiscriminatorValue); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.DeployStatus>(); } },
                { "trigger", n => { Trigger = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.Deploy_trigger>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Deploy_commit>("commit", Commit);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteDateTimeOffsetValue("finishedAt", FinishedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Deploy_image>("image", Image);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.DeployStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.Deploy_trigger>("trigger", Trigger);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
