// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPOST"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPOST"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvSpecificDetailsPOST : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPOST"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPOST? DockerDetailsPOST { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPOST DockerDetailsPOST { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPOST"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPOST? NativeEnvironmentDetailsPOST { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPOST NativeEnvironmentDetailsPOST { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPOST"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPOST CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPOST();
            if("dockerDetailsPOST".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DockerDetailsPOST = new global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPOST();
            }
            else if("nativeEnvironmentDetailsPOST".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.NativeEnvironmentDetailsPOST = new global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPOST();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DockerDetailsPOST != null)
            {
                return DockerDetailsPOST.GetFieldDeserializers();
            }
            else if(NativeEnvironmentDetailsPOST != null)
            {
                return NativeEnvironmentDetailsPOST.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DockerDetailsPOST != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPOST>(null, DockerDetailsPOST);
            }
            else if(NativeEnvironmentDetailsPOST != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPOST>(null, NativeEnvironmentDetailsPOST);
            }
        }
    }
}
#pragma warning restore CS0618
