// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPatch"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPatch"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvSpecificDetailsPatch : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPatch"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPatch? DockerDetailsPatch { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPatch DockerDetailsPatch { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPatch"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPatch? NativeEnvironmentDetailsPatch { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPatch NativeEnvironmentDetailsPatch { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPatch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPatch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPatch();
            if("DockerDetailsPatch".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DockerDetailsPatch = new global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPatch();
            }
            else if("NativeEnvironmentDetailsPatch".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.NativeEnvironmentDetailsPatch = new global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPatch();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DockerDetailsPatch != null)
            {
                return DockerDetailsPatch.GetFieldDeserializers();
            }
            else if(NativeEnvironmentDetailsPatch != null)
            {
                return NativeEnvironmentDetailsPatch.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DockerDetailsPatch != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.DockerDetailsPatch>(null, DockerDetailsPatch);
            }
            else if(NativeEnvironmentDetailsPatch != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.NativeEnvironmentDetailsPatch>(null, NativeEnvironmentDetailsPatch);
            }
        }
    }
}
#pragma warning restore CS0618
