// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetBandwidthSources200ResponseDataItemLabelsTrafficSource
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "total")]
        #pragma warning disable CS1591
        Total,
        #pragma warning restore CS1591
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
        [EnumMember(Value = "websocket")]
        #pragma warning disable CS1591
        Websocket,
        #pragma warning restore CS1591
        [EnumMember(Value = "nat")]
        #pragma warning disable CS1591
        Nat,
        #pragma warning restore CS1591
        [EnumMember(Value = "privatelink")]
        #pragma warning disable CS1591
        Privatelink,
        #pragma warning restore CS1591
    }
}
