// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetBandwidthSources200ResponseDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemLabels? Labels { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemLabels Labels { get; set; }
#endif
        /// <summary>The values property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemValuesItem>? Values { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemValuesItem> Values { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItem"/> and sets the default values.
        /// </summary>
        public GetBandwidthSources200ResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "labels", n => { Labels = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemLabels>(global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemLabels.CreateFromDiscriminatorValue); } },
                { "values", n => { Values = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemValuesItem>(global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemValuesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemLabels>("labels", Labels);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.GetBandwidthSources200ResponseDataItemValuesItem>("values", Values);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
