// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListAvailablePostgresParameterOverrides200ResponseAvailableParameterOverridesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The examples property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Examples { get; set; }
#nullable restore
#else
        public List<string> Examples { get; set; }
#endif
        /// <summary>The maximum value allowed for numeric parameters.</summary>
        public double? MaxValue { get; set; }
        /// <summary>The minimum value allowed for numeric parameters.</summary>
        public double? MinValue { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Whether setting this parameter requires a restart to take effect.</summary>
        public bool? RequiresRestart { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.ListAvailablePostgresParameterOverrides200ResponseAvailableParameterOverridesItem"/> and sets the default values.
        /// </summary>
        public ListAvailablePostgresParameterOverrides200ResponseAvailableParameterOverridesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.ListAvailablePostgresParameterOverrides200ResponseAvailableParameterOverridesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.ListAvailablePostgresParameterOverrides200ResponseAvailableParameterOverridesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.ListAvailablePostgresParameterOverrides200ResponseAvailableParameterOverridesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "examples", n => { Examples = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "maxValue", n => { MaxValue = n.GetDoubleValue(); } },
                { "minValue", n => { MinValue = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "requiresRestart", n => { RequiresRestart = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("examples", Examples);
            writer.WriteDoubleValue("maxValue", MaxValue);
            writer.WriteDoubleValue("minValue", MinValue);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("requiresRestart", RequiresRestart);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
