// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListApplicationFilterValues200ResponseItemFilter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "instance")]
        #pragma warning disable CS1591
        Instance,
        #pragma warning restore CS1591
    }
}
