// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>The compute plan to use. Legacy variants (`*_legacy`) identify grandfathered plans no longer offered for new services. Note that base services on any paid compute plan can&apos;t create preview instances with the `free` plan.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Plan
    {
        [EnumMember(Value = "starter")]
        #pragma warning disable CS1591
        Starter,
        #pragma warning restore CS1591
        [EnumMember(Value = "starter_plus")]
        #pragma warning disable CS1591
        StarterPlus,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard_plus")]
        #pragma warning disable CS1591
        StandardPlus,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro")]
        #pragma warning disable CS1591
        Pro,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro_plus")]
        #pragma warning disable CS1591
        ProPlus,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro_max")]
        #pragma warning disable CS1591
        ProMax,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro_ultra")]
        #pragma warning disable CS1591
        ProUltra,
        #pragma warning restore CS1591
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
        [EnumMember(Value = "starter_legacy")]
        #pragma warning disable CS1591
        StarterLegacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard_legacy")]
        #pragma warning disable CS1591
        StandardLegacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard_plus_legacy")]
        #pragma warning disable CS1591
        StandardPlusLegacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro_legacy")]
        #pragma warning disable CS1591
        ProLegacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro_plus_legacy")]
        #pragma warning disable CS1591
        ProPlusLegacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "0.5c-512mb")]
        #pragma warning disable CS1591
        Value05C512Mb,
        #pragma warning restore CS1591
        [EnumMember(Value = "1c-2g")]
        #pragma warning disable CS1591
        Value1C2G,
        #pragma warning restore CS1591
        [EnumMember(Value = "2c-4g")]
        #pragma warning disable CS1591
        Value2C4G,
        #pragma warning restore CS1591
        [EnumMember(Value = "2c-8g")]
        #pragma warning disable CS1591
        Value2C8G,
        #pragma warning restore CS1591
        [EnumMember(Value = "2c-16g")]
        #pragma warning disable CS1591
        Value2C16G,
        #pragma warning restore CS1591
        [EnumMember(Value = "4c-8g")]
        #pragma warning disable CS1591
        Value4C8G,
        #pragma warning restore CS1591
        [EnumMember(Value = "4c-16g")]
        #pragma warning disable CS1591
        Value4C16G,
        #pragma warning restore CS1591
        [EnumMember(Value = "4c-32g")]
        #pragma warning disable CS1591
        Value4C32G,
        #pragma warning restore CS1591
        [EnumMember(Value = "8c-16g")]
        #pragma warning disable CS1591
        Value8C16G,
        #pragma warning restore CS1591
        [EnumMember(Value = "8c-32g")]
        #pragma warning disable CS1591
        Value8C32G,
        #pragma warning restore CS1591
        [EnumMember(Value = "8c-64g")]
        #pragma warning disable CS1591
        Value8C64G,
        #pragma warning restore CS1591
        [EnumMember(Value = "12c-24g")]
        #pragma warning disable CS1591
        Value12C24G,
        #pragma warning restore CS1591
        [EnumMember(Value = "12c-48g")]
        #pragma warning disable CS1591
        Value12C48G,
        #pragma warning restore CS1591
        [EnumMember(Value = "12c-96g")]
        #pragma warning disable CS1591
        Value12C96G,
        #pragma warning restore CS1591
    }
}
