// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>
    /// Input for creating a database
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostgresPOSTInput : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The databaseName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseName { get; set; }
#nullable restore
#else
        public string DatabaseName { get; set; }
#endif
        /// <summary>The databaseUser property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseUser { get; set; }
#nullable restore
#else
        public string DatabaseUser { get; set; }
#endif
        /// <summary>The Datadog API key for the Datadog agent to monitor the new database.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatadogAPIKey { get; set; }
#nullable restore
#else
        public string DatadogAPIKey { get; set; }
#endif
        /// <summary>Datadog region to use for monitoring the new database. Defaults to &apos;US1&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatadogSite { get; set; }
#nullable restore
#else
        public string DatadogSite { get; set; }
#endif
        /// <summary>The number of gigabytes of disk space to allocate for the database</summary>
        public int? DiskSizeGB { get; set; }
        /// <summary>The enableDiskAutoscaling property</summary>
        public bool? EnableDiskAutoscaling { get; set; }
        /// <summary>The enableHighAvailability property</summary>
        public bool? EnableHighAvailability { get; set; }
        /// <summary>The environmentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentId { get; set; }
#nullable restore
#else
        public string EnvironmentId { get; set; }
#endif
        /// <summary>The ipAllowList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>? IpAllowList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription> IpAllowList { get; set; }
#endif
        /// <summary>The name of the database as it will appear in the Render Dashboard</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the workspace to create the database for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The parameterOverrides property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.PostgresParameterOverrides? ParameterOverrides { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.PostgresParameterOverrides ParameterOverrides { get; set; }
#endif
        /// <summary>The instance type to use. Note that base services on any paid instance type can&apos;t create preview instances with the `free` instance type.</summary>
        public global::Soenneker.Render.OpenApiClient.Models.Plan? Plan { get; set; }
        /// <summary>The readReplicas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.ReadReplicaInput>? ReadReplicas { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.ReadReplicaInput> ReadReplicas { get; set; }
#endif
        /// <summary>The region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The PostgreSQL version</summary>
        public global::Soenneker.Render.OpenApiClient.Models.PostgresVersion? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.PostgresPOSTInput"/> and sets the default values.
        /// </summary>
        public PostgresPOSTInput()
        {
            AdditionalData = new Dictionary<string, object>();
            DatabaseName = "randomly generated";
            DatabaseUser = "randomly generated";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.PostgresPOSTInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.PostgresPOSTInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.PostgresPOSTInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "databaseName", n => { DatabaseName = n.GetStringValue(); } },
                { "databaseUser", n => { DatabaseUser = n.GetStringValue(); } },
                { "datadogAPIKey", n => { DatadogAPIKey = n.GetStringValue(); } },
                { "datadogSite", n => { DatadogSite = n.GetStringValue(); } },
                { "diskSizeGB", n => { DiskSizeGB = n.GetIntValue(); } },
                { "enableDiskAutoscaling", n => { EnableDiskAutoscaling = n.GetBoolValue(); } },
                { "enableHighAvailability", n => { EnableHighAvailability = n.GetBoolValue(); } },
                { "environmentId", n => { EnvironmentId = n.GetStringValue(); } },
                { "ipAllowList", n => { IpAllowList = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>(global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "parameterOverrides", n => { ParameterOverrides = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.PostgresParameterOverrides>(global::Soenneker.Render.OpenApiClient.Models.PostgresParameterOverrides.CreateFromDiscriminatorValue); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.Plan>(); } },
                { "readReplicas", n => { ReadReplicas = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.ReadReplicaInput>(global::Soenneker.Render.OpenApiClient.Models.ReadReplicaInput.CreateFromDiscriminatorValue)?.AsList(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "version", n => { Version = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.PostgresVersion>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("databaseName", DatabaseName);
            writer.WriteStringValue("databaseUser", DatabaseUser);
            writer.WriteStringValue("datadogAPIKey", DatadogAPIKey);
            writer.WriteStringValue("datadogSite", DatadogSite);
            writer.WriteIntValue("diskSizeGB", DiskSizeGB);
            writer.WriteBoolValue("enableDiskAutoscaling", EnableDiskAutoscaling);
            writer.WriteBoolValue("enableHighAvailability", EnableHighAvailability);
            writer.WriteStringValue("environmentId", EnvironmentId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>("ipAllowList", IpAllowList);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.PostgresParameterOverrides>("parameterOverrides", ParameterOverrides);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.Plan>("plan", Plan);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.ReadReplicaInput>("readReplicas", ReadReplicas);
            writer.WriteStringValue("region", Region);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.PostgresVersion>("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
