// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>The PostgreSQL version</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostgresVersion
    {
        [EnumMember(Value = "11")]
        #pragma warning disable CS1591
        OneOne,
        #pragma warning restore CS1591
        [EnumMember(Value = "12")]
        #pragma warning disable CS1591
        OneTwo,
        #pragma warning restore CS1591
        [EnumMember(Value = "13")]
        #pragma warning disable CS1591
        OneThree,
        #pragma warning restore CS1591
        [EnumMember(Value = "14")]
        #pragma warning disable CS1591
        OneFour,
        #pragma warning restore CS1591
        [EnumMember(Value = "15")]
        #pragma warning disable CS1591
        OneFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "16")]
        #pragma warning disable CS1591
        OneSix,
        #pragma warning restore CS1591
        [EnumMember(Value = "17")]
        #pragma warning disable CS1591
        OneSeven,
        #pragma warning restore CS1591
        [EnumMember(Value = "18")]
        #pragma warning disable CS1591
        OneEight,
        #pragma warning restore CS1591
    }
}
