// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>Indicates whether an environment is `unprotected` or `protected`. Only admin users can perform destructive actions in `protected` environments.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProtectedStatus
    {
        [EnumMember(Value = "unprotected")]
        #pragma warning disable CS1591
        Unprotected,
        #pragma warning restore CS1591
        [EnumMember(Value = "protected")]
        #pragma warning disable CS1591
        Protected,
        #pragma warning restore CS1591
    }
}
