// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>This field has been deprecated. previews.generation should be used in its place.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Obsolete("")]
    public enum PullRequestPreviewsEnabled
    {
        [EnumMember(Value = "yes")]
        #pragma warning disable CS1591
        Yes,
        #pragma warning restore CS1591
        [EnumMember(Value = "no")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
    }
}
