// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>type of the resource (ex. web_service or postgres)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RetrieveBlueprint200ResponseResourcesItemType
    {
        [EnumMember(Value = "static_site")]
        #pragma warning disable CS1591
        StaticSite,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_service")]
        #pragma warning disable CS1591
        WebService,
        #pragma warning restore CS1591
        [EnumMember(Value = "private_service")]
        #pragma warning disable CS1591
        PrivateService,
        #pragma warning restore CS1591
        [EnumMember(Value = "background_worker")]
        #pragma warning disable CS1591
        BackgroundWorker,
        #pragma warning restore CS1591
        [EnumMember(Value = "cron_job")]
        #pragma warning disable CS1591
        CronJob,
        #pragma warning restore CS1591
        [EnumMember(Value = "redis")]
        #pragma warning disable CS1591
        Redis,
        #pragma warning restore CS1591
        [EnumMember(Value = "key_value")]
        #pragma warning disable CS1591
        KeyValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "postgres")]
        #pragma warning disable CS1591
        Postgres,
        #pragma warning restore CS1591
        [EnumMember(Value = "environment_group")]
        #pragma warning disable CS1591
        EnvironmentGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "artifact_source")]
        #pragma warning disable CS1591
        ArtifactSource,
        #pragma warning restore CS1591
    }
}
