// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ServiceEventWithCursor_event_detailsMember8_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "canceled")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "successful")]
        #pragma warning disable CS1591
        Successful,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsuccessful")]
        #pragma warning disable CS1591
        Unsuccessful,
        #pragma warning restore CS1591
    }
}
