// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetails"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.CronJobDetails"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetails"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetails"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServiceServiceDetails : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetails"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetails? BackgroundWorkerDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetails BackgroundWorkerDetails { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.CronJobDetails"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.CronJobDetails? CronJobDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.CronJobDetails CronJobDetails { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetails"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetails? PrivateServiceDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetails PrivateServiceDetails { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetails"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetails? StaticSiteDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetails StaticSiteDetails { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails? WebServiceDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails WebServiceDetails { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails();
            if("BackgroundWorkerDetails".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BackgroundWorkerDetails = new global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetails();
            }
            else if("CronJobDetails".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CronJobDetails = new global::Soenneker.Render.OpenApiClient.Models.CronJobDetails();
            }
            else if("PrivateServiceDetails".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PrivateServiceDetails = new global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetails();
            }
            else if("StaticSiteDetails".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.StaticSiteDetails = new global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetails();
            }
            else if("WebServiceDetails".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WebServiceDetails = new global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BackgroundWorkerDetails != null)
            {
                return BackgroundWorkerDetails.GetFieldDeserializers();
            }
            else if(CronJobDetails != null)
            {
                return CronJobDetails.GetFieldDeserializers();
            }
            else if(PrivateServiceDetails != null)
            {
                return PrivateServiceDetails.GetFieldDeserializers();
            }
            else if(StaticSiteDetails != null)
            {
                return StaticSiteDetails.GetFieldDeserializers();
            }
            else if(WebServiceDetails != null)
            {
                return WebServiceDetails.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BackgroundWorkerDetails != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetails>(null, BackgroundWorkerDetails);
            }
            else if(CronJobDetails != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.CronJobDetails>(null, CronJobDetails);
            }
            else if(PrivateServiceDetails != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetails>(null, PrivateServiceDetails);
            }
            else if(StaticSiteDetails != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetails>(null, StaticSiteDetails);
            }
            else if(WebServiceDetails != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails>(null, WebServiceDetails);
            }
        }
    }
}
#pragma warning restore CS0618
