// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ServiceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "static_site")]
        #pragma warning disable CS1591
        Static_site,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_service")]
        #pragma warning disable CS1591
        Web_service,
        #pragma warning restore CS1591
        [EnumMember(Value = "private_service")]
        #pragma warning disable CS1591
        Private_service,
        #pragma warning restore CS1591
        [EnumMember(Value = "background_worker")]
        #pragma warning disable CS1591
        Background_worker,
        #pragma warning restore CS1591
        [EnumMember(Value = "cron_job")]
        #pragma warning disable CS1591
        Cron_job,
        #pragma warning restore CS1591
    }
}
