// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>This field has been deprecated, runtime should be used in its place.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Obsolete("")]
    public enum ServiceEnv
    {
        [EnumMember(Value = "docker")]
        #pragma warning disable CS1591
        Docker,
        #pragma warning restore CS1591
        [EnumMember(Value = "elixir")]
        #pragma warning disable CS1591
        Elixir,
        #pragma warning restore CS1591
        [EnumMember(Value = "go")]
        #pragma warning disable CS1591
        Go,
        #pragma warning restore CS1591
        [EnumMember(Value = "node")]
        #pragma warning disable CS1591
        Node,
        #pragma warning restore CS1591
        [EnumMember(Value = "python")]
        #pragma warning disable CS1591
        Python,
        #pragma warning restore CS1591
        [EnumMember(Value = "ruby")]
        #pragma warning disable CS1591
        Ruby,
        #pragma warning restore CS1591
        [EnumMember(Value = "rust")]
        #pragma warning disable CS1591
        Rust,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
    }
}
