// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceEventWithCursor_event_detailsMember5_reason : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The buildFailed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? BuildFailed { get; set; }
#nullable restore
#else
        public UntypedNode BuildFailed { get; set; }
#endif
        /// <summary>The failure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Failure { get; set; }
#nullable restore
#else
        public UntypedNode Failure { get; set; }
#endif
        /// <summary>The newBuild property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason_newBuild? NewBuild { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason_newBuild NewBuild { get; set; }
#endif
        /// <summary>The newDeploy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? NewDeploy { get; set; }
#nullable restore
#else
        public UntypedNode NewDeploy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason"/> and sets the default values.
        /// </summary>
        public ServiceEventWithCursor_event_detailsMember5_reason()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buildFailed", n => { BuildFailed = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "failure", n => { Failure = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "newBuild", n => { NewBuild = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason_newBuild>(global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason_newBuild.CreateFromDiscriminatorValue); } },
                { "newDeploy", n => { NewDeploy = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("buildFailed", BuildFailed);
            writer.WriteObjectValue<UntypedNode>("failure", Failure);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.ServiceEventWithCursor_event_detailsMember5_reason_newBuild>("newBuild", NewBuild);
            writer.WriteObjectValue<UntypedNode>("newDeploy", NewDeploy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
