// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServicePOST : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autoDeploy property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.AutoDeploy? AutoDeploy { get; set; }
        /// <summary>The repo branch to pull, build, and deploy. If omitted, uses the repository&apos;s default branch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>The buildFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.BuildFilter? BuildFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.BuildFilter BuildFilter { get; set; }
#endif
        /// <summary>The ID of the environment the service belongs to, if any. Obtain an environment&apos;s ID from its Settings page in the Render Dashboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentId { get; set; }
#nullable restore
#else
        public string EnvironmentId { get; set; }
#endif
        /// <summary>The envVars property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.EnvVarInput>? EnvVars { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.EnvVarInput> EnvVars { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Image? Image { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Image Image { get; set; }
#endif
        /// <summary>The service&apos;s name. Must be unique within the workspace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the workspace the service belongs to. Obtain your workspace&apos;s ID from its Settings page in the Render Dashboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The service&apos;s repository URL. Do not specify a branch in this string (use the `branch` parameter instead).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Repo { get; set; }
#nullable restore
#else
        public string Repo { get; set; }
#endif
        /// <summary>The rootDir property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootDir { get; set; }
#nullable restore
#else
        public string RootDir { get; set; }
#endif
        /// <summary>The secretFiles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.SecretFileInput>? SecretFiles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.SecretFileInput> SecretFiles { get; set; }
#endif
        /// <summary>The serviceDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails? ServiceDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails ServiceDetails { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.ServiceType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.ServicePOST"/> and sets the default values.
        /// </summary>
        public ServicePOST()
        {
            AdditionalData = new Dictionary<string, object>();
            AutoDeploy = global::Soenneker.Render.OpenApiClient.Models.AutoDeploy.Yes;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.ServicePOST"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.ServicePOST CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.ServicePOST();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoDeploy", n => { AutoDeploy = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.AutoDeploy>(); } },
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "buildFilter", n => { BuildFilter = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.BuildFilter>(global::Soenneker.Render.OpenApiClient.Models.BuildFilter.CreateFromDiscriminatorValue); } },
                { "envVars", n => { EnvVars = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.EnvVarInput>(global::Soenneker.Render.OpenApiClient.Models.EnvVarInput.CreateFromDiscriminatorValue)?.AsList(); } },
                { "environmentId", n => { EnvironmentId = n.GetStringValue(); } },
                { "image", n => { Image = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Image>(global::Soenneker.Render.OpenApiClient.Models.Image.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "repo", n => { Repo = n.GetStringValue(); } },
                { "rootDir", n => { RootDir = n.GetStringValue(); } },
                { "secretFiles", n => { SecretFiles = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.SecretFileInput>(global::Soenneker.Render.OpenApiClient.Models.SecretFileInput.CreateFromDiscriminatorValue)?.AsList(); } },
                { "serviceDetails", n => { ServiceDetails = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails>(global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.AutoDeploy>("autoDeploy", AutoDeploy);
            writer.WriteStringValue("branch", Branch);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.BuildFilter>("buildFilter", BuildFilter);
            writer.WriteStringValue("environmentId", EnvironmentId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.EnvVarInput>("envVars", EnvVars);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Image>("image", Image);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteStringValue("repo", Repo);
            writer.WriteStringValue("rootDir", RootDir);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.SecretFileInput>("secretFiles", SecretFiles);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails>("serviceDetails", ServiceDetails);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPOST"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPOST"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPOST"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPOST"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPOST"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ServicePOST_serviceDetails : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPOST"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPOST? BackgroundWorkerDetailsPOST { get; set; }
#nullable restore
#else
            public global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPOST BackgroundWorkerDetailsPOST { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPOST"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPOST? CronJobDetailsPOST { get; set; }
#nullable restore
#else
            public global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPOST CronJobDetailsPOST { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPOST"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPOST? PrivateServiceDetailsPOST { get; set; }
#nullable restore
#else
            public global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPOST PrivateServiceDetailsPOST { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPOST"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPOST? StaticSiteDetailsPOST { get; set; }
#nullable restore
#else
            public global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPOST StaticSiteDetailsPOST { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPOST"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPOST? WebServiceDetailsPOST { get; set; }
#nullable restore
#else
            public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPOST WebServiceDetailsPOST { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Render.OpenApiClient.Models.ServicePOST.ServicePOST_serviceDetails();
                if("backgroundWorkerDetailsPOST".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BackgroundWorkerDetailsPOST = new global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPOST();
                }
                else if("cronJobDetailsPOST".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CronJobDetailsPOST = new global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPOST();
                }
                else if("privateServiceDetailsPOST".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PrivateServiceDetailsPOST = new global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPOST();
                }
                else if("staticSiteDetailsPOST".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.StaticSiteDetailsPOST = new global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPOST();
                }
                else if("webServiceDetailsPOST".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WebServiceDetailsPOST = new global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPOST();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BackgroundWorkerDetailsPOST != null)
                {
                    return BackgroundWorkerDetailsPOST.GetFieldDeserializers();
                }
                else if(CronJobDetailsPOST != null)
                {
                    return CronJobDetailsPOST.GetFieldDeserializers();
                }
                else if(PrivateServiceDetailsPOST != null)
                {
                    return PrivateServiceDetailsPOST.GetFieldDeserializers();
                }
                else if(StaticSiteDetailsPOST != null)
                {
                    return StaticSiteDetailsPOST.GetFieldDeserializers();
                }
                else if(WebServiceDetailsPOST != null)
                {
                    return WebServiceDetailsPOST.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(BackgroundWorkerDetailsPOST != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPOST>(null, BackgroundWorkerDetailsPOST);
                }
                else if(CronJobDetailsPOST != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPOST>(null, CronJobDetailsPOST);
                }
                else if(PrivateServiceDetailsPOST != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPOST>(null, PrivateServiceDetailsPOST);
                }
                else if(StaticSiteDetailsPOST != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPOST>(null, StaticSiteDetailsPOST);
                }
                else if(WebServiceDetailsPOST != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPOST>(null, WebServiceDetailsPOST);
                }
            }
        }
    }
}
#pragma warning restore CS0618
