// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ServerPortProtocol
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TCP")]
        #pragma warning disable CS1591
        Tcp,
        #pragma warning restore CS1591
        [EnumMember(Value = "UDP")]
        #pragma warning disable CS1591
        Udp,
        #pragma warning restore CS1591
    }
}
