// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ServiceTypeShort
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "static")]
        #pragma warning disable CS1591
        Static,
        #pragma warning restore CS1591
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
        [EnumMember(Value = "pserv")]
        #pragma warning disable CS1591
        Pserv,
        #pragma warning restore CS1591
        [EnumMember(Value = "worker")]
        #pragma warning disable CS1591
        Worker,
        #pragma warning restore CS1591
        [EnumMember(Value = "cron")]
        #pragma warning disable CS1591
        Cron,
        #pragma warning restore CS1591
    }
}
