// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Service : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autoDeploy property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.AutoDeploy? AutoDeploy { get; set; }
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>The buildFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.BuildFilter? BuildFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.BuildFilter BuildFilter { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The URL to view the service in the Render Dashboard</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DashboardUrl { get; set; }
#nullable restore
#else
        public string DashboardUrl { get; set; }
#endif
        /// <summary>The environmentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvironmentId { get; set; }
#nullable restore
#else
        public string EnvironmentId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The imagePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImagePath { get; set; }
#nullable restore
#else
        public string ImagePath { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The notifyOnFail property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.NotifySetting? NotifyOnFail { get; set; }
        /// <summary>The ownerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The registryCredential property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.RegistryCredentialSummary? RegistryCredential { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.RegistryCredentialSummary RegistryCredential { get; set; }
#endif
        /// <summary>The repo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Repo { get; set; }
#nullable restore
#else
        public string Repo { get; set; }
#endif
        /// <summary>The rootDir property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootDir { get; set; }
#nullable restore
#else
        public string RootDir { get; set; }
#endif
        /// <summary>The serviceDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails? ServiceDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails ServiceDetails { get; set; }
#endif
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The suspended property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.ServiceSuspended? Suspended { get; set; }
        /// <summary>The suspenders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.SuspenderType?>? Suspenders { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.SuspenderType?> Suspenders { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.ServiceType? Type { get; set; }
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.Service"/> and sets the default values.
        /// </summary>
        public Service()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.Service"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.Service CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.Service();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoDeploy", n => { AutoDeploy = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.AutoDeploy>(); } },
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "buildFilter", n => { BuildFilter = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.BuildFilter>(global::Soenneker.Render.OpenApiClient.Models.BuildFilter.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "dashboardUrl", n => { DashboardUrl = n.GetStringValue(); } },
                { "environmentId", n => { EnvironmentId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "imagePath", n => { ImagePath = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notifyOnFail", n => { NotifyOnFail = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.NotifySetting>(); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "registryCredential", n => { RegistryCredential = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.RegistryCredentialSummary>(global::Soenneker.Render.OpenApiClient.Models.RegistryCredentialSummary.CreateFromDiscriminatorValue); } },
                { "repo", n => { Repo = n.GetStringValue(); } },
                { "rootDir", n => { RootDir = n.GetStringValue(); } },
                { "serviceDetails", n => { ServiceDetails = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails>(global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails.CreateFromDiscriminatorValue); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "suspended", n => { Suspended = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceSuspended>(); } },
                { "suspenders", n => { Suspenders = n.GetCollectionOfEnumValues<global::Soenneker.Render.OpenApiClient.Models.SuspenderType>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceType>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.AutoDeploy>("autoDeploy", AutoDeploy);
            writer.WriteStringValue("branch", Branch);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.BuildFilter>("buildFilter", BuildFilter);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("dashboardUrl", DashboardUrl);
            writer.WriteStringValue("environmentId", EnvironmentId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("imagePath", ImagePath);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.NotifySetting>("notifyOnFail", NotifyOnFail);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.RegistryCredentialSummary>("registryCredential", RegistryCredential);
            writer.WriteStringValue("repo", Repo);
            writer.WriteStringValue("rootDir", RootDir);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.ServiceServiceDetails>("serviceDetails", ServiceDetails);
            writer.WriteStringValue("slug", Slug);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceSuspended>("suspended", Suspended);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Render.OpenApiClient.Models.SuspenderType>("suspenders", Suspenders);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceType>("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
