// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPost"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPost"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPost"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPost"/>, <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPost"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServicePostServiceDetails : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPost"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPost? BackgroundWorkerDetailsPost { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPost BackgroundWorkerDetailsPost { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPost"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPost? CronJobDetailsPost { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPost CronJobDetailsPost { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPost"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPost? PrivateServiceDetailsPost { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPost PrivateServiceDetailsPost { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPost"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPost? StaticSiteDetailsPost { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPost StaticSiteDetailsPost { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPost"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPost? WebServiceDetailsPost { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPost WebServiceDetailsPost { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.ServicePostServiceDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.ServicePostServiceDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Render.OpenApiClient.Models.ServicePostServiceDetails();
            if("BackgroundWorkerDetailsPost".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BackgroundWorkerDetailsPost = new global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPost();
            }
            else if("CronJobDetailsPost".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CronJobDetailsPost = new global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPost();
            }
            else if("PrivateServiceDetailsPost".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PrivateServiceDetailsPost = new global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPost();
            }
            else if("StaticSiteDetailsPost".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.StaticSiteDetailsPost = new global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPost();
            }
            else if("WebServiceDetailsPost".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WebServiceDetailsPost = new global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPost();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BackgroundWorkerDetailsPost != null)
            {
                return BackgroundWorkerDetailsPost.GetFieldDeserializers();
            }
            else if(CronJobDetailsPost != null)
            {
                return CronJobDetailsPost.GetFieldDeserializers();
            }
            else if(PrivateServiceDetailsPost != null)
            {
                return PrivateServiceDetailsPost.GetFieldDeserializers();
            }
            else if(StaticSiteDetailsPost != null)
            {
                return StaticSiteDetailsPost.GetFieldDeserializers();
            }
            else if(WebServiceDetailsPost != null)
            {
                return WebServiceDetailsPost.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BackgroundWorkerDetailsPost != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.BackgroundWorkerDetailsPost>(null, BackgroundWorkerDetailsPost);
            }
            else if(CronJobDetailsPost != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.CronJobDetailsPost>(null, CronJobDetailsPost);
            }
            else if(PrivateServiceDetailsPost != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.PrivateServiceDetailsPost>(null, PrivateServiceDetailsPost);
            }
            else if(StaticSiteDetailsPost != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.StaticSiteDetailsPost>(null, StaticSiteDetailsPost);
            }
            else if(WebServiceDetailsPost != null)
            {
                writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPost>(null, WebServiceDetailsPost);
            }
        }
    }
}
#pragma warning restore CS0618
