// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>The auto-deploy trigger value after it was re-enabled</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServiceEventWithCursorEventDetailsAutoDeployEnabledNewTrigger
    {
        [EnumMember(Value = "commit")]
        #pragma warning disable CS1591
        Commit,
        #pragma warning restore CS1591
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
        [EnumMember(Value = "checksPass")]
        #pragma warning disable CS1591
        ChecksPass,
        #pragma warning restore CS1591
    }
}
