// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskRunWithCursor_taskRun : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attempts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_attempts>? Attempts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_attempts> Attempts { get; set; }
#endif
        /// <summary>The completedAt property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The parentTaskRunId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentTaskRunId { get; set; }
#nullable restore
#else
        public string ParentTaskRunId { get; set; }
#endif
        /// <summary>The retries property</summary>
        public int? Retries { get; set; }
        /// <summary>The rootTaskRunId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootTaskRunId { get; set; }
#nullable restore
#else
        public string RootTaskRunId { get; set; }
#endif
        /// <summary>The startedAt property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_status? Status { get; set; }
        /// <summary>The taskId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskId { get; set; }
#nullable restore
#else
        public string TaskId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun"/> and sets the default values.
        /// </summary>
        public TaskRunWithCursor_taskRun()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attempts", n => { Attempts = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_attempts>(global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_attempts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "parentTaskRunId", n => { ParentTaskRunId = n.GetStringValue(); } },
                { "retries", n => { Retries = n.GetIntValue(); } },
                { "rootTaskRunId", n => { RootTaskRunId = n.GetStringValue(); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_status>(); } },
                { "taskId", n => { TaskId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_attempts>("attempts", Attempts);
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("parentTaskRunId", ParentTaskRunId);
            writer.WriteIntValue("retries", Retries);
            writer.WriteStringValue("rootTaskRunId", RootTaskRunId);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.TaskRunWithCursor_taskRun_status>("status", Status);
            writer.WriteStringValue("taskId", TaskId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
