// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TriggerBuildSourceBuild201ResponseBuildRunRuntime
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "docker")]
        #pragma warning disable CS1591
        Docker,
        #pragma warning restore CS1591
        [EnumMember(Value = "elixir")]
        #pragma warning disable CS1591
        Elixir,
        #pragma warning restore CS1591
        [EnumMember(Value = "go")]
        #pragma warning disable CS1591
        Go,
        #pragma warning restore CS1591
        [EnumMember(Value = "node")]
        #pragma warning disable CS1591
        Node,
        #pragma warning restore CS1591
        [EnumMember(Value = "python")]
        #pragma warning disable CS1591
        Python,
        #pragma warning restore CS1591
        [EnumMember(Value = "ruby")]
        #pragma warning disable CS1591
        Ruby,
        #pragma warning restore CS1591
        [EnumMember(Value = "rust")]
        #pragma warning disable CS1591
        Rust,
        #pragma warning restore CS1591
    }
}
