// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebServiceDetailsPATCH : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cache property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Cache? Cache { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Cache Cache { get; set; }
#endif
        /// <summary>The envSpecificDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPATCH? EnvSpecificDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPATCH EnvSpecificDetails { get; set; }
#endif
        /// <summary>The healthCheckPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthCheckPath { get; set; }
#nullable restore
#else
        public string HealthCheckPath { get; set; }
#endif
        /// <summary>The ipAllowList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>? IpAllowList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription> IpAllowList { get; set; }
#endif
        /// <summary>The maintenanceMode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode? MaintenanceMode { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode MaintenanceMode { get; set; }
#endif
        /// <summary>The maximum amount of time (in seconds) that Render waits for your application process to exit gracefully after sending it a SIGTERM signal.</summary>
        public int? MaxShutdownDelaySeconds { get; set; }
        /// <summary>The instance type to use. Legacy variants (`*_legacy`) identify grandfathered plans no longer offered for new services. Note that base services on any paid instance type can&apos;t create preview instances with the `free` instance type.</summary>
        public global::Soenneker.Render.OpenApiClient.Models.Plan? Plan { get; set; }
        /// <summary>The preDeployCommand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreDeployCommand { get; set; }
#nullable restore
#else
        public string PreDeployCommand { get; set; }
#endif
        /// <summary>The previews property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Previews? Previews { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Previews Previews { get; set; }
#endif
        /// <summary>This field has been deprecated. previews.generation should be used in its place.</summary>
        [Obsolete("")]
        public global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled? PullRequestPreviewsEnabled { get; set; }
        /// <summary>Controls whether render.com subdomains are available for the service</summary>
        public global::Soenneker.Render.OpenApiClient.Models.RenderSubdomainPolicy? RenderSubdomainPolicy { get; set; }
        /// <summary>Runtime</summary>
        public global::Soenneker.Render.OpenApiClient.Models.ServiceRuntime? Runtime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPATCH"/> and sets the default values.
        /// </summary>
        public WebServiceDetailsPATCH()
        {
            AdditionalData = new Dictionary<string, object>();
            PullRequestPreviewsEnabled = global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled.No;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPATCH"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPATCH CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsPATCH();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cache", n => { Cache = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Cache>(global::Soenneker.Render.OpenApiClient.Models.Cache.CreateFromDiscriminatorValue); } },
                { "envSpecificDetails", n => { EnvSpecificDetails = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPATCH>(global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPATCH.CreateFromDiscriminatorValue); } },
                { "healthCheckPath", n => { HealthCheckPath = n.GetStringValue(); } },
                { "ipAllowList", n => { IpAllowList = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>(global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription.CreateFromDiscriminatorValue)?.AsList(); } },
                { "maintenanceMode", n => { MaintenanceMode = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode>(global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode.CreateFromDiscriminatorValue); } },
                { "maxShutdownDelaySeconds", n => { MaxShutdownDelaySeconds = n.GetIntValue(); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.Plan>(); } },
                { "preDeployCommand", n => { PreDeployCommand = n.GetStringValue(); } },
                { "previews", n => { Previews = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Previews>(global::Soenneker.Render.OpenApiClient.Models.Previews.CreateFromDiscriminatorValue); } },
                { "pullRequestPreviewsEnabled", n => { PullRequestPreviewsEnabled = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled>(); } },
                { "renderSubdomainPolicy", n => { RenderSubdomainPolicy = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.RenderSubdomainPolicy>(); } },
                { "runtime", n => { Runtime = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceRuntime>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Cache>("cache", Cache);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetailsPATCH>("envSpecificDetails", EnvSpecificDetails);
            writer.WriteStringValue("healthCheckPath", HealthCheckPath);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>("ipAllowList", IpAllowList);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode>("maintenanceMode", MaintenanceMode);
            writer.WriteIntValue("maxShutdownDelaySeconds", MaxShutdownDelaySeconds);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.Plan>("plan", Plan);
            writer.WriteStringValue("preDeployCommand", PreDeployCommand);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Previews>("previews", Previews);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled>("pullRequestPreviewsEnabled", PullRequestPreviewsEnabled);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.RenderSubdomainPolicy>("renderSubdomainPolicy", RenderSubdomainPolicy);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceRuntime>("runtime", Runtime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
