// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebServiceDetails : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autoscaling property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_autoscaling? Autoscaling { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_autoscaling Autoscaling { get; set; }
#endif
        /// <summary>The buildPlan property</summary>
        public global::Soenneker.Render.OpenApiClient.Models.BuildPlan? BuildPlan { get; set; }
        /// <summary>The cache property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Cache? Cache { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Cache Cache { get; set; }
#endif
        /// <summary>The disk property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_disk? Disk { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_disk Disk { get; set; }
#endif
        /// <summary>This field has been deprecated, runtime should be used in its place.</summary>
        [Obsolete("")]
        public global::Soenneker.Render.OpenApiClient.Models.ServiceEnv? Env { get; set; }
        /// <summary>The envSpecificDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetails? EnvSpecificDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetails EnvSpecificDetails { get; set; }
#endif
        /// <summary>The healthCheckPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthCheckPath { get; set; }
#nullable restore
#else
        public string HealthCheckPath { get; set; }
#endif
        /// <summary>The ipAllowList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>? IpAllowList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription> IpAllowList { get; set; }
#endif
        /// <summary>The maintenanceMode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode? MaintenanceMode { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode MaintenanceMode { get; set; }
#endif
        /// <summary>The maximum amount of time (in seconds) that Render waits for your application process to exit gracefully after sending it a SIGTERM signal.</summary>
        public int? MaxShutdownDelaySeconds { get; set; }
        /// <summary>For a *manually* scaled service, this is the number of instances the service is scaled to. DOES NOT indicate the number of running instances for an *autoscaled* service.</summary>
        public int? NumInstances { get; set; }
        /// <summary>The openPorts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Render.OpenApiClient.Models.ServerPort>? OpenPorts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Render.OpenApiClient.Models.ServerPort> OpenPorts { get; set; }
#endif
        /// <summary>The parentServer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Resource? ParentServer { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Resource ParentServer { get; set; }
#endif
        /// <summary>The instance type to use. Note that base services on any paid instance type can&apos;t create preview instances with the `free` instance type.</summary>
        public global::Soenneker.Render.OpenApiClient.Models.Plan? Plan { get; set; }
        /// <summary>The previews property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.Previews? Previews { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.Previews Previews { get; set; }
#endif
        /// <summary>This field has been deprecated. previews.generation should be used in its place.</summary>
        [Obsolete("")]
        public global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled? PullRequestPreviewsEnabled { get; set; }
        /// <summary>Defaults to &quot;oregon&quot;</summary>
        public global::Soenneker.Render.OpenApiClient.Models.Region? Region { get; set; }
        /// <summary>Controls whether render.com subdomains are available for the service</summary>
        public global::Soenneker.Render.OpenApiClient.Models.RenderSubdomainPolicy? RenderSubdomainPolicy { get; set; }
        /// <summary>Runtime</summary>
        public global::Soenneker.Render.OpenApiClient.Models.ServiceRuntime? Runtime { get; set; }
        /// <summary>The SSH address for the service. Only present for services that have SSH enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SshAddress { get; set; }
#nullable restore
#else
        public string SshAddress { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails"/> and sets the default values.
        /// </summary>
        public WebServiceDetails()
        {
            AdditionalData = new Dictionary<string, object>();
            BuildPlan = global::Soenneker.Render.OpenApiClient.Models.BuildPlan.Starter;
            PullRequestPreviewsEnabled = global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled.No;
            Region = global::Soenneker.Render.OpenApiClient.Models.Region.Oregon;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoscaling", n => { Autoscaling = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_autoscaling>(global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_autoscaling.CreateFromDiscriminatorValue); } },
                { "buildPlan", n => { BuildPlan = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.BuildPlan>(); } },
                { "cache", n => { Cache = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Cache>(global::Soenneker.Render.OpenApiClient.Models.Cache.CreateFromDiscriminatorValue); } },
                { "disk", n => { Disk = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_disk>(global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_disk.CreateFromDiscriminatorValue); } },
                { "env", n => { Env = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceEnv>(); } },
                { "envSpecificDetails", n => { EnvSpecificDetails = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetails>(global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetails.CreateFromDiscriminatorValue); } },
                { "healthCheckPath", n => { HealthCheckPath = n.GetStringValue(); } },
                { "ipAllowList", n => { IpAllowList = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>(global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription.CreateFromDiscriminatorValue)?.AsList(); } },
                { "maintenanceMode", n => { MaintenanceMode = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode>(global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode.CreateFromDiscriminatorValue); } },
                { "maxShutdownDelaySeconds", n => { MaxShutdownDelaySeconds = n.GetIntValue(); } },
                { "numInstances", n => { NumInstances = n.GetIntValue(); } },
                { "openPorts", n => { OpenPorts = n.GetCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.ServerPort>(global::Soenneker.Render.OpenApiClient.Models.ServerPort.CreateFromDiscriminatorValue)?.AsList(); } },
                { "parentServer", n => { ParentServer = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Resource>(global::Soenneker.Render.OpenApiClient.Models.Resource.CreateFromDiscriminatorValue); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.Plan>(); } },
                { "previews", n => { Previews = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.Previews>(global::Soenneker.Render.OpenApiClient.Models.Previews.CreateFromDiscriminatorValue); } },
                { "pullRequestPreviewsEnabled", n => { PullRequestPreviewsEnabled = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled>(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.Region>(); } },
                { "renderSubdomainPolicy", n => { RenderSubdomainPolicy = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.RenderSubdomainPolicy>(); } },
                { "runtime", n => { Runtime = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceRuntime>(); } },
                { "sshAddress", n => { SshAddress = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_autoscaling>("autoscaling", Autoscaling);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.BuildPlan>("buildPlan", BuildPlan);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Cache>("cache", Cache);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetails_disk>("disk", Disk);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceEnv>("env", Env);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.EnvSpecificDetails>("envSpecificDetails", EnvSpecificDetails);
            writer.WriteStringValue("healthCheckPath", HealthCheckPath);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.CidrBlockAndDescription>("ipAllowList", IpAllowList);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.MaintenanceMode>("maintenanceMode", MaintenanceMode);
            writer.WriteIntValue("maxShutdownDelaySeconds", MaxShutdownDelaySeconds);
            writer.WriteIntValue("numInstances", NumInstances);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Render.OpenApiClient.Models.ServerPort>("openPorts", OpenPorts);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Resource>("parentServer", ParentServer);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.Plan>("plan", Plan);
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.Previews>("previews", Previews);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.PullRequestPreviewsEnabled>("pullRequestPreviewsEnabled", PullRequestPreviewsEnabled);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.Region>("region", Region);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.RenderSubdomainPolicy>("renderSubdomainPolicy", RenderSubdomainPolicy);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.ServiceRuntime>("runtime", Runtime);
            writer.WriteStringValue("sshAddress", SshAddress);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
