// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebServiceDetailsAutoscalingCriteria : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cpu property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteriaCpu? Cpu { get; set; }
#nullable restore
#else
        public global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteriaCpu Cpu { get; set; }
#endif
        /// <summary>The memory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Memory { get; set; }
#nullable restore
#else
        public string Memory { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteria"/> and sets the default values.
        /// </summary>
        public WebServiceDetailsAutoscalingCriteria()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteria"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteria CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteria();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cpu", n => { Cpu = n.GetObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteriaCpu>(global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteriaCpu.CreateFromDiscriminatorValue); } },
                { "memory", n => { Memory = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Render.OpenApiClient.Models.WebServiceDetailsAutoscalingCriteriaCpu>("cpu", Cpu);
            writer.WriteStringValue("memory", Memory);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
