// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Render.OpenApiClient.Models
{
    /// <summary>The runtime environment for the workflow (e.g., node, python, etc.).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowWithCursor_workflow_buildConfig_runtime
    {
        [EnumMember(Value = "elixir")]
        #pragma warning disable CS1591
        Elixir,
        #pragma warning restore CS1591
        [EnumMember(Value = "go")]
        #pragma warning disable CS1591
        Go,
        #pragma warning restore CS1591
        [EnumMember(Value = "node")]
        #pragma warning disable CS1591
        Node,
        #pragma warning restore CS1591
        [EnumMember(Value = "python")]
        #pragma warning disable CS1591
        Python,
        #pragma warning restore CS1591
        [EnumMember(Value = "ruby")]
        #pragma warning disable CS1591
        Ruby,
        #pragma warning restore CS1591
    }
}
