// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Render.OpenApiClient.MetricsStream.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Render.OpenApiClient.MetricsStream
{
    /// <summary>
    /// Builds and executes requests for operations under \metrics-stream
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetricsStreamRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Render.OpenApiClient.metricsStream.item collection</summary>
        /// <param name="position">The ID of the workspace to return metrics stream information for</param>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.MetricsStream.Item.WithOwnerItemRequestBuilder"/></returns>
        public global::Soenneker.Render.OpenApiClient.MetricsStream.Item.WithOwnerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("ownerId", position);
                return new global::Soenneker.Render.OpenApiClient.MetricsStream.Item.WithOwnerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.MetricsStream.MetricsStreamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetricsStreamRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics-stream", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.MetricsStream.MetricsStreamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetricsStreamRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics-stream", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
