// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Render.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Render.OpenApiClient.Services.Item.Deploys
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeploysPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If `clear`, Render clears the service&apos;s build cache before deploying. This can be useful if you&apos;re experiencing issues with your build.</summary>
        public global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody_clearCache? ClearCache { get; set; }
        /// <summary>The SHA of a specific Git commit to deploy for a service. Defaults to the latest commit on the service&apos;s connected branch.Note that deploying a specific commit with this endpoint does not disable autodeploys for the service.You can toggle autodeploys for your service with the [Update service](https://api-docs.render.com/reference/update-service) endpoint or in the Render Dashboard.Not supported for cron jobs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitId { get; set; }
#nullable restore
#else
        public string CommitId { get; set; }
#endif
        /// <summary>Controls deployment behavior when triggering a deploy.- `deploy_only`: Deploy the last successful build without rebuilding (minimizes downtime)- `build_and_deploy`: Build new code and deploy it (default behavior when not specified)**Note:** `deploy_only` cannot be combined with `commitId`, `imageUrl` or `clearCache` parameters,as those are build related fields.</summary>
        public global::Soenneker.Render.OpenApiClient.Models.DeployMode? DeployMode { get; set; }
        /// <summary>The URL of the image to deploy for an image-backed service.The host, repository, and image name all must match the currently configured image for the service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageUrl { get; set; }
#nullable restore
#else
        public string ImageUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody"/> and sets the default values.
        /// </summary>
        public DeploysPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            ClearCache = global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody_clearCache.Do_not_clear;
            DeployMode = global::Soenneker.Render.OpenApiClient.Models.DeployMode.Build_and_deploy;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clearCache", n => { ClearCache = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody_clearCache>(); } },
                { "commitId", n => { CommitId = n.GetStringValue(); } },
                { "deployMode", n => { DeployMode = n.GetEnumValue<global::Soenneker.Render.OpenApiClient.Models.DeployMode>(); } },
                { "imageUrl", n => { ImageUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Services.Item.Deploys.DeploysPostRequestBody_clearCache>("clearCache", ClearCache);
            writer.WriteStringValue("commitId", CommitId);
            writer.WriteEnumValue<global::Soenneker.Render.OpenApiClient.Models.DeployMode>("deployMode", DeployMode);
            writer.WriteStringValue("imageUrl", ImageUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
