// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Render.OpenApiClient.Blueprints;
using Soenneker.Render.OpenApiClient.CronJobs;
using Soenneker.Render.OpenApiClient.Disks;
using Soenneker.Render.OpenApiClient.EnvGroups;
using Soenneker.Render.OpenApiClient.Environments;
using Soenneker.Render.OpenApiClient.Events;
using Soenneker.Render.OpenApiClient.KeyValue;
using Soenneker.Render.OpenApiClient.Logs;
using Soenneker.Render.OpenApiClient.Maintenance;
using Soenneker.Render.OpenApiClient.Metrics;
using Soenneker.Render.OpenApiClient.MetricsStream;
using Soenneker.Render.OpenApiClient.NotificationSettings;
using Soenneker.Render.OpenApiClient.Organizations;
using Soenneker.Render.OpenApiClient.Owners;
using Soenneker.Render.OpenApiClient.Postgres;
using Soenneker.Render.OpenApiClient.Projects;
using Soenneker.Render.OpenApiClient.Redis;
using Soenneker.Render.OpenApiClient.Registrycredentials;
using Soenneker.Render.OpenApiClient.Sandboxes;
using Soenneker.Render.OpenApiClient.Services;
using Soenneker.Render.OpenApiClient.TaskRuns;
using Soenneker.Render.OpenApiClient.Tasks;
using Soenneker.Render.OpenApiClient.Users;
using Soenneker.Render.OpenApiClient.Webhooks;
using Soenneker.Render.OpenApiClient.Workflows;
using Soenneker.Render.OpenApiClient.Workflowversions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Render.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RenderOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The blueprints property</summary>
        public global::Soenneker.Render.OpenApiClient.Blueprints.BlueprintsRequestBuilder Blueprints
        {
            get => new global::Soenneker.Render.OpenApiClient.Blueprints.BlueprintsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cronJobs property</summary>
        public global::Soenneker.Render.OpenApiClient.CronJobs.CronJobsRequestBuilder CronJobs
        {
            get => new global::Soenneker.Render.OpenApiClient.CronJobs.CronJobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disks property</summary>
        public global::Soenneker.Render.OpenApiClient.Disks.DisksRequestBuilder Disks
        {
            get => new global::Soenneker.Render.OpenApiClient.Disks.DisksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The envGroups property</summary>
        public global::Soenneker.Render.OpenApiClient.EnvGroups.EnvGroupsRequestBuilder EnvGroups
        {
            get => new global::Soenneker.Render.OpenApiClient.EnvGroups.EnvGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The environments property</summary>
        public global::Soenneker.Render.OpenApiClient.Environments.EnvironmentsRequestBuilder Environments
        {
            get => new global::Soenneker.Render.OpenApiClient.Environments.EnvironmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Render.OpenApiClient.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Render.OpenApiClient.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keyValue property</summary>
        public global::Soenneker.Render.OpenApiClient.KeyValue.KeyValueRequestBuilder KeyValue
        {
            get => new global::Soenneker.Render.OpenApiClient.KeyValue.KeyValueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logs property</summary>
        public global::Soenneker.Render.OpenApiClient.Logs.LogsRequestBuilder Logs
        {
            get => new global::Soenneker.Render.OpenApiClient.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maintenance property</summary>
        public global::Soenneker.Render.OpenApiClient.Maintenance.MaintenanceRequestBuilder Maintenance
        {
            get => new global::Soenneker.Render.OpenApiClient.Maintenance.MaintenanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::Soenneker.Render.OpenApiClient.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::Soenneker.Render.OpenApiClient.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metricsStream property</summary>
        public global::Soenneker.Render.OpenApiClient.MetricsStream.MetricsStreamRequestBuilder MetricsStream
        {
            get => new global::Soenneker.Render.OpenApiClient.MetricsStream.MetricsStreamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notificationSettings property</summary>
        public global::Soenneker.Render.OpenApiClient.NotificationSettings.NotificationSettingsRequestBuilder NotificationSettings
        {
            get => new global::Soenneker.Render.OpenApiClient.NotificationSettings.NotificationSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::Soenneker.Render.OpenApiClient.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::Soenneker.Render.OpenApiClient.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The owners property</summary>
        public global::Soenneker.Render.OpenApiClient.Owners.OwnersRequestBuilder Owners
        {
            get => new global::Soenneker.Render.OpenApiClient.Owners.OwnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The postgres property</summary>
        public global::Soenneker.Render.OpenApiClient.Postgres.PostgresRequestBuilder Postgres
        {
            get => new global::Soenneker.Render.OpenApiClient.Postgres.PostgresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Soenneker.Render.OpenApiClient.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Soenneker.Render.OpenApiClient.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The redis property</summary>
        public global::Soenneker.Render.OpenApiClient.Redis.RedisRequestBuilder Redis
        {
            get => new global::Soenneker.Render.OpenApiClient.Redis.RedisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The registrycredentials property</summary>
        public global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder Registrycredentials
        {
            get => new global::Soenneker.Render.OpenApiClient.Registrycredentials.RegistrycredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sandboxes property</summary>
        public global::Soenneker.Render.OpenApiClient.Sandboxes.SandboxesRequestBuilder Sandboxes
        {
            get => new global::Soenneker.Render.OpenApiClient.Sandboxes.SandboxesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The services property</summary>
        public global::Soenneker.Render.OpenApiClient.Services.ServicesRequestBuilder Services
        {
            get => new global::Soenneker.Render.OpenApiClient.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The taskRuns property</summary>
        public global::Soenneker.Render.OpenApiClient.TaskRuns.TaskRunsRequestBuilder TaskRuns
        {
            get => new global::Soenneker.Render.OpenApiClient.TaskRuns.TaskRunsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Soenneker.Render.OpenApiClient.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Soenneker.Render.OpenApiClient.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Render.OpenApiClient.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Render.OpenApiClient.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Render.OpenApiClient.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Render.OpenApiClient.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflows property</summary>
        public global::Soenneker.Render.OpenApiClient.Workflows.WorkflowsRequestBuilder Workflows
        {
            get => new global::Soenneker.Render.OpenApiClient.Workflows.WorkflowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflowversions property</summary>
        public global::Soenneker.Render.OpenApiClient.Workflowversions.WorkflowversionsRequestBuilder Workflowversions
        {
            get => new global::Soenneker.Render.OpenApiClient.Workflowversions.WorkflowversionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Render.OpenApiClient.RenderOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RenderOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.render.com/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
